In [46]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [47]:
df = pd.read_csv('startup.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [48]:
real_x = df.iloc[:,0:4].values
real_y = df.iloc[:,4].values

In [49]:
le = LabelEncoder()
real_x[:,3] = le.fit_transform(real_x[:,3])
ohe = OneHotEncoder(categorical_features=[3])
real_x = ohe.fit_transform(real_x).toarray()

c:\users\sumit\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [34]:
x_training,x_testing,y_training,y_testing = train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [50]:
real_x = real_x[:,1:]

In [51]:
real_x =np.append(arr=np.ones((50,1)).astype(int),values=real_x,axis=1)

In [52]:
x_training,x_testing,y_training,y_testing = train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [56]:
opt_x = real_x[:,[0,3]]
opt_x

array([[1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 9.1749160e+04],
       [1.0000000e+00, 8.6419700e+04],
       [1.0000000e+00, 7.6253860e+04],
       [1.0000000e+00, 7.8389470e+04],
       [1.0000000e+00, 7.3994560e+04],
       [1.0000000e+00, 6.7532530e+04],
       [1.0000000e+00, 7.7044010e+04],
       [1.0000000e+00, 6.

In [57]:
reg_ols = sm.OLS(exog=opt_x,endog=real_y).fit()

In [43]:
reg_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Thu, 05 Sep 2019   Prob (F-statistic):           1.34e-27
Time:                        02:43:47   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [14]:
MLR = LinearRegression()
MLR.fit(x_training,y_training)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
MLR.predict(x_testing)

array([104282.76472168, 132536.88499213, 133910.85007763,  72584.77489413,
       179920.92761886, 114549.31079235,  66444.43261347,  98404.96840123,
       114499.82808599, 169367.50639891,  96522.62539977,  88040.67182871,
       110949.99405521,  90419.18978512, 128020.4625006 ])

In [16]:
y_testing

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [58]:
reg_ols.predict(x_testing[:,[0,3]])

array([105460.14271464, 135036.08586475, 136096.36397105,  72861.58000754,
       180116.65707807, 110633.79960036,  66314.86331588, 101261.18102569,
       112245.81324567, 170433.97345032,  96440.90176556,  88342.27936946,
       113385.70276482,  88694.29012885, 127413.41482014])

In [ ]:
def bbakward_elimination(x,sl):
    nVars = len(x[0])
    temp = np.zeros((50,6)).astype(int)
    for i in range(nVars):
        reg_ols = sm.OLS(exog=x,endog=y).fit()
        max_val = max(reg_ols.pvalues).astype(float)
        adjr_before = reg_ols.rsquared_adj.astype(float)
        if max_val > sl:
            for j in range(nVars-i):
                if reg_ols.pvalues[j].astype(float) == max_val:
                    temp[:,j] = x[:,j]
                    x = np.delete(x,j,axis=1)
        for j in p:
            if j == max(p):
                np.delete(x,j,axis=1)