In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

In [2]:
df = pd.read_csv('startup.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
real_x = df.iloc[:,:4].values
real_y = df.iloc[:,4].values


In [4]:
le = LabelEncoder()
real_x[:,3]=le.fit_transform(real_x[:,3])

In [5]:
ohe = OneHotEncoder(categorical_features=[3])
real_x = ohe.fit_transform(real_x).toarray()

c:\users\sumit\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\sumit\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [6]:
training_x,testing_x,training_y,testing_x = train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [7]:
real_x = real_x[:,1:]

In [8]:
row,col = df.shape

In [9]:
real_x = np.append(arr=np.ones((row,1)).astype(int),values=real_x,axis=1)

In [10]:
opt_x =real_x[:,[0,1,2,3,4,5]]
opt_x

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [11]:
def backward_elimination(x,sl):
    n_vars = len(x[0])
    for i in range(n_vars):
        print(x[0])
        reg_ols = sm.OLS(exog=x,endog=real_y).fit()
        max_val = max(reg_ols.pvalues).astype(float)
        if max_val > sl:
            for j in range(n_vars-i):
                if reg_ols.pvalues[j].astype(float) == max_val:
                    x = np.delete(x,j,axis=1)
        else:
            break
    print(reg_ols.summary())
    return x

In [12]:
opt_x = backward_elimination(opt_x,0.05)
opt_x

[1.000000e+00 0.000000e+00 1.000000e+00 1.653492e+05 1.368978e+05
 4.717841e+05]
[1.000000e+00 0.000000e+00 1.653492e+05 1.368978e+05 4.717841e+05]
[1.000000e+00 1.653492e+05 1.368978e+05 4.717841e+05]
[1.000000e+00 1.653492e+05 4.717841e+05]
[1.000000e+00 1.653492e+05]
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Fri, 06 Sep 2019   Prob (F-statistic):           3.50e-32
Time:                        08:32:16   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:  

array([[1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 9.1749160e+04],
       [1.0000000e+00, 8.6419700e+04],
       [1.0000000e+00, 7.6253860e+04],
       [1.0000000e+00, 7.8389470e+04],
       [1.0000000e+00, 7.3994560e+04],
       [1.0000000e+00, 6.7532530e+04],
       [1.0000000e+00, 7.7044010e+04],
       [1.0000000e+00, 6.

In [15]:
model = sm.OLS(exog=opt_x,endog=real_y).fit()

In [13]:
training_x,testing_x,training_y,testing_y = train_test_split(opt_x,real_y,test_size=0.2,random_state=0)

In [16]:
x = model.predict(testing_x)

In [18]:
testing_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [19]:
x-testing_y

array([  2177.76271464,  -9223.31413525, -10025.58602895,  -4937.24999246,
       -10933.73292193,   5625.48960036, -14914.19668412,   3777.62102569,
         1893.56324567,   4246.03345032])

In [20]:
model.tvalues

array([19.32028767, 29.15113899])